sudo: required
dist: trusty
language: ruby
rvm:
- 2.0.0
- 2.1
- 2.2
- 2.3.0
- 2.4.0

after_success:
- >
  [ "${TRAVIS_PULL_REQUEST}" != "false" ] &&
  [ "${TRAVIS_RUBY_VERSION}" = "2.0.0" ] &&
    PULL_REQUEST_ID=${TRAVIS_PULL_REQUEST} \
      bundle exec pronto run -f github_status github_pr -c origin/${TRAVIS_BRANCH}
