sudo: required
before_install: gem update --system
dist: trusty
language: ruby
rvm:
- 2.1
- 2.2
- 2.3
- 2.4
- 2.5

after_success:
- >
  [ "${TRAVIS_PULL_REQUEST}" != "false" ] &&
  [ "${TRAVIS_RUBY_VERSION}" = "2.1" ] &&
    PRONTO_PULL_REQUEST_ID=${TRAVIS_PULL_REQUEST} \
      bundle exec pronto run -f github_status github_pr -c origin/${TRAVIS_BRANCH}
- bundle exec codeclimate-test-reporter

addons:
  code_climate:
    repo_token: 3d676246ffa66d3fdef6253a9870431b1a2da04e9ecb25486c08a38823c37b6a
